# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S5BZxFhxulKkjai3pKe0FiOA14hYxcOW
"""

import streamlit as st
from predictor import predict_manipulator

st.set_page_config(page_title="Earnings Manipulation Detection", layout="centered")

st.title("📊 Earnings Manipulation Prediction (XGBoost)")
st.write("Enter Beneish ratio values and run prediction")

features = ['DSRI','GMI','AQI','SGI','DEPI','SGAI','ACCR','LEVI']
inputs = {}

for feature in features:
    inputs[feature] = st.number_input(
        label=feature,
        value=1.0,
        format="%.4f"
    )

if st.button("Run Prediction"):
    result = predict_manipulator(inputs)

    st.subheader("Prediction Result")

    if result["prediction"] == "Yes":
        st.error("⚠️ High Risk: Possible Earnings Manipulation")
    else:
        st.success("✅ Low Risk: Not a Manipulator")

    st.write("Manipulation Probability:", result["probability"])