# -*- coding: utf-8 -*-
"""Predictor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BU-OANY0jm8DPgOBQnr54BOxd-VKm_5i
"""

import joblib
import numpy as np
import os
import xgboost as xgb

# Get directory of this file
BASE_DIR = os.path.dirname(os.path.abspath(__file__))

MODEL_PATH = os.path.join(BASE_DIR, "xgb_model.pkl")

if not os.path.exists(MODEL_PATH):
    raise FileNotFoundError(f"xgb_model.pkl not found in {BASE_DIR}")

# Load trained XGBoost sklearn model
model = joblib.load(MODEL_PATH)

FEATURES = ['DSRI','GMI','AQI','SGI','DEPI','SGAI','ACCR','LEVI']

def predict_manipulator(input_dict):
    # Prepare input
    X = np.array([[input_dict[f] for f in FEATURES]], dtype=np.float32)

    # Convert to DMatrix (SAFE for cloud)
    dmatrix = xgb.DMatrix(X, feature_names=FEATURES)

    # Use Booster directly
    booster = model.get_booster()
    prob = float(booster.predict(dmatrix)[0])

    prediction = 1 if prob >= 0.5 else 0

    return {
        "prediction": "Yes" if prediction == 1 else "No",
        "probability": round(prob, 3)
    }